### ISSUE TITLE
[优化] 自动填充 F3+C 复制的命令

### ISSUE THREAD

**Issue by youzi-2333** [Shrans/Stronghold-Locator#2]
### 描述
在用户使用 F3+C 复制坐标后，自动对其进行填充，即使程序不在前台。
如果可以的话，自动在有一个坐标时进行点斜式估算法、两个坐标时进行点斜式交点法计算坐标，并使用窗口右下角弹窗推送（Win10/11 的右下角弹窗不会使游戏暂停）。

### 技术信息
在程序启动时，读取一次剪贴板，将剪贴板内容存放到变量 `clip` 中。
接下来每 500ms 读取一次剪贴板，如果内容与 `clip` 的内容一致，则循环读取；如果不一致，则判断此内容是否以 `/execute in ` 打头，如果是，则跳出循环，并填充坐标；否则再次保存 `clip`，并循环读取，直到有合法坐标。

以下是一个 Python 的程序伪代码：
```py
# 初始化
clip = GetClipBoard()

# （应该是在一个线程里面）循环执行
while True:
    text = GetClipBoard()
    if text == clip:
        if text.isLegal: #是否合法，即是否以 /execute in 打头
            break #合法，跳出循环
        else:
            clip = text #不合法，继续运行
    time.sleep(0.5)
# ...（将它填充到文本框，然后尝试使用估算法计算，并右下角推送）
# 再来一遍
while True:
    text = GetClipBoard()
    if text == clip:
        if text.isLegal: #是否合法，即是否以 /execute in 打头
            break #合法，跳出循环
        else:
            clip = text #不合法，继续运行
    time.sleep(0.5)
# ...（将它填充到文本框，然后尝试使用交点法计算，并右下角推送）
quit() #退出程序
```

**Comment by lidongxun967** [comment]
这个功能容易误操作，使用快捷键输入的形式我认为会更好

**Comment by lidongxun967** [comment]
这个功能容易误操作，使用快捷键输入的形式我认为会更好

**Comment by lidongxun967** [comment]
另外可以加入q群：874827045讨论

**Comment by youzi-2333** [comment]
额，确实如果用户不小心碰到 `F3+C` 的话容易误操作，毕竟 `F3` 和 `C` 都在键盘左边……
快捷键的话我暂时不确定能不能实现，因为它会输入到 MC 窗口里面而不是定位器里面（

**Comment by lidongxun967** [comment]
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by lidongxun967** [comment]
可以的，我将在3个版本左右加入该功能，谢谢你的提议
